language: php

php:
  - '7.0'

services:
  - mysql

before_script:
  # Set up Composer
  - composer self-update || true
  - composer install --prefer-dist
  # Set up permissions
  - chmod -R 0777 src/
  # Set up Mysql
  - mysql -e "" -uroot
  - mysql -e 'CREAT database candy_shop;' -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON candy_shop.* TO 'travis'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  # Tell php to shut up :P
  - echo 'date.timezone = "Asia/Shanghai"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: phpunit -c phpunit.xml --coverage-text
