language: php

php:
  - '7.0'

services:
  - mysql

addons:
  mariadb: '10.1'

before_script:
  # Set up Composer
  - composer self-update || true
  - composer install --prefer-dist
  # Set up permissions
  - chmod -R 0777 src/
  # Set up Mysql
  - mysql -e "" -uroot
  - mysql -e 'CREATE database candy_shop;' -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON candy_shop.* TO 'travis'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -uroot
  - mysql -e "use candy_shop; source ./tests/dbscript/candy_shop_2016-06-07.sql" -uroot
  # Tell php to shut up :P
  - echo 'date.timezone = "Asia/Shanghai"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: phpunit -c phpunit.xml --coverage-text
