language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

before_script:
  # Set up Composer
  - composer self-update || true
  - composer install --prefer-dist
  # Set up permissions
  - chmod -R 0777 src/
  # Set up Mysql
  - mysql -e "" -u root
  - mysql -e 'CREAT database candy_shop;'
  - mysql -e "GRANT ALL PRIVILEGES ON candy_shop.* TO 'travis'@'localhost';" -uroot
  - mysql -e "FLUSH PRIVILEGES;" -u root
  # Tell php to shut up :P
  - echo 'date.timezone = "Asia/Shanghai"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  notifications:
    email:
      recipients:
        - qdladoooo@gmail.com
        on_failure: always

  script: phpunit -c phpunit.xml --coverage-text
